######################################################################################################
# This file is generated when `botfront up` is invoked.                                              #
# Changes in .botfront/botfront.yml and .botfront/docker-compose-template.yml will be reflected here #
######################################################################################################

version: '3.0'
services:
  botfront:
    image: 'botfront-private:latest'
    container_name: project-creation-test-botfront-app
    restart: always
    networks:
      - project-creation-test-network
    ports:
      - '8888:3000'
      - '3030:3030'
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      PORT: 3000
  
  mongo:
    image: 'mongo:latest'
    container_name: project-creation-test-mongo
    restart: always
    networks:
      - project-creation-test-network
    ports:
      - '27017:27017'
    env_file:
      - .env
networks:
  project-creation-test-network: {}
